<a href="https://colab.research.google.com/github/bhargavnarasimha14/Bhargav-sai/blob/main/Anumala_Bhargav_Sai_Narasimha__In_class_Excercise_03_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 In-class Exercise 3**

The purpose of this exercise is to explore various aspects of text analysis, including feature extraction, feature selection, and text similarity ranking.

**Expectations**:
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

**Total points**: 40

**Deadline**: This in-class exercise is due at the end of Friday, at 11:59 PM.

**Late submissions will have a penalty of 10% of the marks for each day of late submission. , and no requests will be answered. Manage your time accordingly.**

**Please check that the link you submitted can be opened and points to the correct assignment.**

## Question 1 (10 Points)
Describe an interesting **text classification or text mining task** and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features. **Your dataset must be text.**

# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:


Text Classification Task: Division of movie reviews and the ability to determine the division from a positive or negative viewpoint.

The goal is to divide movie reviews into segments having different degrees of sentiment. The dataset contains one column: review_text.the column review_text displays the text of the movie review.

Features:

Bag of Words (BoW):

Reduces the text into words and then the features into words where the value is the frequency of the words in the text ignoring how the words are arranged and using concern with spelling and grammar. In such a manner, any individual word of the text is treated as one other variable.
Why it's useful: It helps in capturing presence or absence of words in terms of different levels of sentiments. For example, the word "excellent" is positive by comparing with a word "boring".

Term Frequency-Inverse Document Frequency
Calculates a score for a evch word with vision of how frequent that thr word is going to get used in a document relative to how often the word is used in some corpus.
Why it's useful: In a broader sense, stemming leads to the reduction of the relative frequency of stopwords which they replace with a corresponding stem, and an increase of the ‘token’, that is less frequent words or the effective words that define the sentiment–oriented terms in a model.
Sentiment Polarity Scores:

Contains Negopus, VADER and other dictionaries which rate each accruacy as having positive, negative or neutral sentiment.
Why it's useful: It helps in computing the sentiments polarity and it is more convenient for model to distinguish between Very Positive – Positive – Neutral – Negative – Very Negative words.



N-grams (Bigrams and Trigrams):

Explores two to three words at a time to provide more contextual understanding than when using only the word. For instance, “not good” is in some ways dissimilar to the individual sentiment of the words “not” and “good”.
Why it's useful: Facilitates the computation of contextual context and idioms that guide the determination of polarity. Most useful for the identification of negations and phrases where the sense changes.
Word Embeddings (Word2Vec, GloVe):

Is a method with words being represented as a densely distributed points in a Hilbert space. Supporters use it to capture semantic meaning and linking of the words being compared against one another.
Why it's useful: We have gained a deeper reflection of how an embedding works because it helps capture the similarities and relationships among words, for example between “amazing and wonderful.”
This feature set embodies different aspects of the text allowing the model to match, decipher meaning of the words used and determine the sentiment.


N-grams (Bigrams and Trigrams):

When used, it involves two to three words of the word to give more sense into it than using only the word. For example, not good is to some degree different from the words not and good as individual sentiments.
Why it's useful: Assists in compute contextual context and idioms which are useful while obtaining polarity. Best for the detection of negations and phrases in which the sign changes whether positive or negative.
Word Embeddings (Word2Vec, GloVe):

methods with words being characterized as a collection of points in a Hilbert space of high density. Some of the supporters have utilised its ability to capture semantic meaning and linking of the words that are used in constructing comparators against the competing words.
Why it's useful: Personally, we have reached a better understanding of an embedding for it provides insights on how words are similar, and concepts such as differentiation between “amazing and wonderful.”
This feature set is actually the different facets of the text through which the model can reproduce, the meaning of words used, and the feeling.




'''

## Question 2 (10 Points)
Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [ ]:
import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.sentiment import SentimentIntensityAnalyzer
from gensim.models import Word2Vec
import nltk
# downloading vader from nltk
nltk.download('vader_lexicon')
# Loading the dataset
data = pd.read_csv('IMDB Dataset.csv')
# text preprocessing
def preprocesstext(text):
    text = re.sub(r'<br />', ' ', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = text.lower().strip()
    return text
# review preprocessing
data['cleaned_review'] = data['review'].apply(preprocesstext)
print("\nPreprocessed Reviews:")
print(data['cleaned_review'].head())
# Bag of Words
bow_vectorizer = CountVectorizer()
bow_features = bow_vectorizer.fit_transform(data['cleaned_review'])
print("\nBag of Words Features:")
print(bow_features.toarray())
print("Feature Names (BoW):", bow_vectorizer.get_feature_names_out())
# termfrequency-inverse document frequenct
tfidf_vectorizer = TfidfVectorizer()
tfidf_features = tfidf_vectorizer.fit_transform(data['cleaned_review'])
print("\nTF-IDF Features:")
print(tfidf_features.toarray())
print("Feature Names (TF-IDF):", tfidf_vectorizer.get_feature_names_out())
sia = SentimentIntensityAnalyzer()
data['sentiment_score'] = data['cleaned_review'].apply(lambda x: sia.polarity_scores(x)['compound'])
print("\nSentiment Polarity Scores:")
print(data[['cleaned_review', 'sentiment_score']].head())
tokenized_reviews = [review.split() for review in data['cleaned_review']]
word2vec_model = Word2Vec(sentences=tokenized_reviews, vector_size=100, window=5, min_count=1, workers=4)
# output
print("\nWord Embeddings of the word ""film"":")
print(word2vec_model.wv['film'])


[nltk_data] Downloading package vader_lexicon to /root/nltk_data...



Preprocessed Reviews:
0    one of the other reviewers has mentioned that ...
1    a wonderful little production   the filming te...
2    i thought this was a wonderful way to spend ti...
3    basically theres a family where a little boy j...
4    petter matteis love in the time of money is a ...
Name: cleaned_review, dtype: object

Bag of Words Features:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Feature Names (BoW): ['aaargh' 'aaliyah' 'aamir' ... 'zulu' 'zwick' 'zzzzzzzzzzzzzzzzzz']

TF-IDF Features:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Feature Names (TF-IDF): ['aaargh' 'aaliyah' 'aamir' ... 'zulu' 'zwick' 'zzzzzzzzzzzzzzzzzz']

Sentiment Polarity Scores:
                                      cleaned_review  sentiment_score
0  one of the other reviewers has mentioned that ...          -0.99

## Question 3 (10 points):
Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [ ]:
# You code here (Please add comments in the code):
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import chi2
from sklearn.preprocessing import LabelEncoder
# creating sentiment column
data['sentiment'] = data['sentiment_score'].apply(lambda x: 'positive' if x > 0 else 'negative')
# termfrequency-inverse document frequency
# adding max feautures
tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X = tfidf_vectorizer.fit_transform(data['cleaned_review'])
le = LabelEncoder()
y = le.fit_transform(data['sentiment'])
chi2_scores, p_values = chi2(X, y)
# Creating data frame
feature_scores = pd.DataFrame({
    'feature': tfidf_vectorizer.get_feature_names_out(),
    'chi2_score': chi2_scores,
    'p_value': p_values
})
feature_scores = feature_scores.sort_values('chi2_score', ascending=False)
print("Top 20 most important features:")
print(feature_scores.head(20))
n_features_to_keep = 1000
top_features = feature_scores.head(n_features_to_keep)['feature'].tolist()
# creating tf-idf matrix
tfidf_vectorizer_selected = TfidfVectorizer(vocabulary=top_features)
X_selected = tfidf_vectorizer_selected.fit_transform(data['cleaned_review'])
print(f"\nShape of the feature matrix after selection: {X_selected.shape}")


Top 20 most important features:
        feature  chi2_score   p_value
4950      worst    5.831144  0.015745
327         bad    4.368241  0.036615
1934      great    3.052084  0.080634
4419   terrible    2.680154  0.101606
3775      santa    2.664460  0.102613
2915     murder    2.603728  0.106613
2441     killer    2.460590  0.116735
4794        war    2.323549  0.127429
2986  nightmare    2.308360  0.128680
411        best    2.224079  0.135874
2132   horrible    2.210124  0.137108
4929  wonderful    2.112090  0.146140
4808      waste    2.043392  0.152868
4749   violence    1.999900  0.157310
4996    zombies    1.959476  0.161569
2988         no    1.959320  0.161586
2443    killing    1.900476  0.168025
3305       poor    1.861230  0.172483
1329       dull    1.860828  0.172529
2136     horror    1.839258  0.175038

Shape of the feature matrix after selection: (999, 1000)


## Question 4 (10 points):
Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [ ]:
# You code here (Please add comments in the code):
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from transformers import BertTokenizer, BertModel
import torch
# loading the dataset
data = pd.read_csv('IMDB Dataset.csv')
# getting bert embeddings
def get_bert_embedding(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).squeeze().numpy()
# loading bert
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')
print("Generating BERT embeddings")
embeddings = []
for review in data['review'][:1000]:  # Limit to first 1000 reviews for efficiency
    embedding = get_bert_embedding(review, model, tokenizer)
    embeddings.append(embedding)
# convert to array
embeddings = np.array(embeddings)
query = "A great science fiction movie with amazing special effects"
query_embedding = get_bert_embedding(query, model, tokenizer)
similarities = cosine_similarity([query_embedding], embeddings)[0]
data['similarity'] = similarities
data_sorted = data.sort_values('similarity', ascending=False)
print("\nTop 10 most similar reviews to the given query:")
for i, row in data_sorted.head(10).iterrows():
    print(f"Similarity: {row['similarity']:.4f}")
    print(f"Review: {row['review'][:200]}...")
    print()
data_sorted.to_csv('similarityresults.csv', index=False)
print("results saved as a csv file")


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Generating BERT embeddings


# Mandatory Question

**Important: Reflective Feedback on this exercise**

Please provide your thoughts and feedback on the exercises you completed in this assignment. Consider the following points in your response:

Learning Experience: Describe your overall learning experience in working on extracting features from text data. What were the key concepts or techniques you found most beneficial in understanding the process?

Challenges Encountered: Were there specific difficulties in completing this exercise?

Relevance to Your Field of Study: How does this exercise relate to the field of NLP?

**(Your submission will not be graded if this question is left unanswered)**



In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

Understood concepts such as bad of words and TF_IDF and chi square method and some of the tasks i encountered
are i came to know that some tasks are resource expensive and this assignment is relevant to field of study
and improved my understanding towards nlp and python libraries and now i came to know that by using nlp we can
gain bussiness insights.



'''